export default {
    chofer: {},
    isEditing: false,
    chofer_id_anterior: null,
    form: {
        id: "",
        fecha: "",
        chofer_id: "",
        numero_interno: "",
        observaciones: "",
        total_liquidacion: "",
        movimientos: [],
        gastos: [],
        anticipos: [],
    },
    removedMovimientos: [],
    removedAnticipos: [],
    removedGastos: [],
    choferes: [],
    flotas: [],
    clientes: [],
    tipoViajes: [],
    provincias: [],
    departamentos: [],
    localidades: [],
    retencionGanancias: [],
    condicionesIva: [],
    retencionIngresoBrutos: [],
    tipoDocumentos: [],
    movimientos: [],
    anticipos: [],
    gastos: [],
    proveedores: [],
    planCuentas: [],
    errors: {}
};
