export default {
    chofer: {},
    form: {
        id: "",
        fecha: "",
        chofer_id: "",
        numero_interno: "",
        observaciones: "",
        total_liquidacion: "",
        movimientos:[],
        gastos:[],
        anticipos:[],
    },
    choferes: [],
    flotas: [],
    clientes: [],
    tipoViajes: [],
    provincias: [],
    departamentos: [],
    localidades: [],
    retencionGanancias: [],
    condicionesIva: [],
    retencionIngresoBrutos: [],
    tipoDocumentos: [],
    movimientos: [],
    anticipos: [],
    gastos: [],
    proveedores: [],
    planCuentas: [],
    errors: {}
};
