export default {
    cliente: {},
    isEditing: false,
    chofer_id_anterior: null,
    cliente_id_anterior: null,
    formCliente:{
        id: "",
        fecha: "",
        cliente_id: "",
        numero_interno: "",
        observaciones: "",
        total_recibo: "",
        movimientos: [],
    },
    choferes: [],
    flotas: [],
    clientes: [],
    tipoViajes: [],
    provincias: [],
    departamentos: [],
    localidades: [],
    retencionGanancias: [],
    condicionesIva: [],
    retencionIngresoBrutos: [],
    tipoDocumentos: [],
    movimientos: [],
    anticipos: [],
    gastos: [],
    proveedores: [],
    planCuentas: [],
    errors: {}
};
